import Link from 'next/link';
import {Leaf,ArrowRight,FileCheck2,TrendingUp,ClipboardList,FlaskConical,ExternalLink,ShieldCheck,AlertCircle} from 'lucide-react';
import targets from '../../data/public/rco-targets.json';
import market from '../../data/public/rec-market-observations.json';
import coverage from '../../data/public/data-coverage.json';

const current = targets.values.find(x=>x.financial_year==='2026-27');
const latest = market.observations[market.observations.length-1];
const labels:Record<string,string>={
 facility_monthly_kwh:'Electricity consumption',
 open_access_captive_drawal:'Open-access & captive records',
 renewable_instruments:'Renewable energy evidence',
 actual_tariffs_contracts:'Actual tariffs & contracts',
 audit_signoff:'Review and sign-off'
};
export default function Home(){
return <main className="min-h-screen">
<header className="bg-[#103f30] text-white"><div className="max-w-6xl mx-auto px-5 py-5 flex flex-wrap items-center justify-between gap-4"><Link href="/" className="flex items-center gap-3"><span className="rounded-xl bg-[#2a8864] p-2"><Leaf size={24}/></span><span><strong className="block text-xl">GreenComply</strong><span className="text-xs text-green-100">Renewable energy intelligence</span></span></Link><nav aria-label="Main navigation" className="flex flex-wrap items-center gap-2 text-sm"><Link aria-current="page" href="/" className="rounded-lg bg-white text-[#103f30] px-4 py-2 font-semibold">Overview</Link><Link href="/data" className="rounded-lg px-4 py-2 hover:bg-white/10">Explore sources</Link><Link href="/scenario" className="rounded-lg px-4 py-2 hover:bg-white/10">Scenario Lab</Link></nav></div></header>
<div className="max-w-6xl mx-auto px-4 md:px-8 py-8 md:py-12 space-y-8">
<section className="rounded-3xl bg-[#103f30] text-white p-7 md:p-10"><span className="inline-block rounded-full bg-white/15 px-3 py-1 text-xs font-semibold mb-4">START HERE · PUBLIC DATA</span><h1 className="text-3xl md:text-5xl font-bold max-w-3xl leading-tight">Know what the data says. Know what is still missing.</h1><p className="mt-4 text-green-100 max-w-2xl">Explore published Indian renewable-energy references, understand the evidence needed for your facility, and try an illustrative scenario—all in one guided journey.</p><div className="flex flex-wrap gap-3 mt-7"><Link href="#published" className="inline-flex items-center gap-2 bg-white text-[#103f30] font-semibold rounded-xl px-5 py-3">Explore published data <ArrowRight size={17}/></Link><Link href="#readiness" className="inline-flex items-center gap-2 border border-white/50 rounded-xl px-5 py-3">What data do I need?</Link></div></section>
<section aria-label="How GreenComply works"><p className="text-xs tracking-widest font-bold text-[#47715d] mb-3">YOUR JOURNEY</p><div className="grid md:grid-cols-3 gap-3">{[{n:'01',title:'Understand',body:'Start with published targets and historical market observations.'},{n:'02',title:'Check readiness',body:'See which facility records are required and why.'},{n:'03',title:'Explore scenarios',body:'Use a clearly labelled demo calculator to understand possible outcomes.'}].map(x=><div className="card" key={x.n}><span className="text-[#21855e] font-bold text-sm">{x.n}</span><h2 className="font-bold text-lg mt-2">{x.title}</h2><p className="text-sm text-[#52675c] mt-1">{x.body}</p></div>)}</div></section>
<section id="published" className="scroll-mt-6 space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs tracking-widest font-bold text-[#47715d]">STEP 1 · UNDERSTAND</p><h2 className="text-2xl md:text-3xl font-bold mt-1">What do published sources tell us?</h2><p className="text-sm text-[#52675c] mt-2">These are reference datasets, not a company's actual compliance position.</p></div><Link href="/data" className="text-[#145c44] font-semibold inline-flex gap-1 items-center">View all sources <ArrowRight size={16}/></Link></div><div className="grid md:grid-cols-2 gap-4"><article className="card space-y-3"><div className="flex items-center gap-2 text-[#145c44]"><FileCheck2 size={19}/><span className="font-semibold">Renewable consumption target</span></div><p className="text-4xl font-bold">{current?current.target_percent+'%':'Not available'}</p><p className="text-sm text-[#52675c]">Published total for FY 2026–27. Applicability and eligible consumption must be assessed for each entity.</p><span className="inline-block text-xs bg-green-100 text-green-900 rounded-full px-3 py-1">Published reference · not facility-verified</span><div><a className="text-sm underline text-[#145c44] inline-flex items-center gap-1" href={targets.sources[1].url} target="_blank" rel="noopener noreferrer">Ministry of Power source <ExternalLink size={13}/></a></div></article><article className="card space-y-3"><div className="flex items-center gap-2 text-[#145c44]"><TrendingUp size={19}/><span className="font-semibold">REC market observation</span></div><p className="text-4xl font-bold">{latest?'₹'+latest.cleared_price_inr_per_rec+'/REC':'Not available'}</p><p className="text-sm text-[#52675c]">Historical exchange-cleared price on {latest?.date??'an unavailable date'}; not a live quote or guaranteed procurement cost.</p><span className="inline-block text-xs bg-blue-100 text-blue-900 rounded-full px-3 py-1">Historical market observation</span><div><a className="text-sm underline text-[#145c44] inline-flex items-center gap-1" href={market.source.url} target="_blank" rel="noopener noreferrer">Exchange source <ExternalLink size={13}/></a></div></article></div><p className="text-xs text-[#52675c]">JSON snapshot: {coverage.as_of}. Other public sources, including grid emission factors, still require extraction and validation.</p></section>
<section id="readiness" className="scroll-mt-6 space-y-4"><div><p className="text-xs tracking-widest font-bold text-[#47715d]">STEP 2 · CHECK READINESS</p><h2 className="text-2xl md:text-3xl font-bold mt-1">Can we assess your facility yet?</h2><p className="text-sm text-[#52675c] mt-2">Not from public data alone. These customer-owned records are required for an evidence-based assessment.</p></div><div className="rounded-2xl bg-amber-50 border border-amber-200 p-4 flex gap-3"><AlertCircle className="shrink-0 text-amber-800" size={21}/><div><strong className="text-amber-950">Facility assessment: not ready</strong><p className="text-sm text-amber-900 mt-1">No actual customer consumption or renewable procurement evidence is connected. GreenComply will not manufacture a compliance result.</p></div></div><div className="grid md:grid-cols-2 gap-3">{coverage.missing_private.map((x,i)=><div className="card" key={x.id}><div className="flex justify-between items-start gap-2"><h3 className="font-semibold">{i+1}. {labels[x.id]??x.id}</h3><span className="text-xs text-amber-900 bg-amber-100 rounded-full px-2 py-1 whitespace-nowrap">Needed</span></div><p className="text-sm text-[#52675c] mt-2"><strong>Get it from:</strong> {x.owner}</p><p className="text-sm text-[#52675c] mt-2">{x.access}</p><p className="text-sm text-red-800 mt-3"><strong>Without it:</strong> {x.impact}</p></div>)}</div><Link href="/data" className="inline-flex items-center gap-2 text-[#145c44] font-semibold">Explore complete data coverage <ArrowRight size={16}/></Link></section>
<section className="rounded-3xl bg-[#e7f2ea] border border-[#cce3d3] p-7 md:p-9 flex flex-wrap items-center justify-between gap-5"><div className="max-w-2xl"><p className="text-xs tracking-widest font-bold text-[#47715d]">STEP 3 · TRY IT</p><h2 className="text-2xl md:text-3xl font-bold mt-2">Explore a scenario without real facility data</h2><p className="text-sm text-[#52675c] mt-3">The Scenario Lab preserves the existing calculator with fictional facilities and editable assumptions. Its results are illustrative—not verified compliance, carbon accounting or procurement advice.</p></div><Link href="/scenario" className="inline-flex items-center gap-2 rounded-xl bg-[#145c44] text-white font-semibold px-5 py-3">Open Scenario Lab <FlaskConical size={18}/></Link></section>
<footer className="border-t pt-5 pb-7 text-xs text-[#52675c] flex flex-wrap justify-between gap-3"><span className="inline-flex gap-2 items-center"><ShieldCheck size={16}/> Source-linked public data · No customer data stored</span><span>GreenComply MVP · Not a statutory filing</span></footer>
</div></main>;
}
